import { chromium } from 'playwright';
const z = Number(process.argv[2] ?? '-1.5');
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-webgpu', '--ignore-gpu-blocklist', '--use-angle=d3d11'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto('http://127.0.0.1:5188/?scene=beach&hud=0&mode=surfel&bake=0');
await page.waitForFunction(() => !!window.__water && document.querySelector('#loading-overlay')?.hidden, null, { timeout: 240000 });
const prof = await page.evaluate((z) => window.__water.profile(z), z);
console.log('profile z=' + z + ' (x: h-level):', prof.filter(p => p[1] > -0.3 && p[1] < 0.5).map(p => p[0] + ':' + p[1]).join(' '));
const t0 = Date.now();
const r = await page.evaluate((z) => window.__water.simRow(z), z);
console.log('simRow took', Date.now() - t0, 'ms', JSON.stringify(r));
await browser.close();
